#! /bin/sh

# Launch sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Set bspwm workspaces
bspc monitor -d one two three four five six

bspc config border_width         2
bspc config window_gap          60
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Bspwm starting rules
bspc rule -a Gimp desktop='^8' state='floating' follow=on

# Dracula (colors)
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#50fa7b"
bspc config presel_feedback_color "#6272a4"
